==3517== ---Thread-Announcement------------------------------------------
==3517== 
==3517== Thread #2 was created
==3517==    at 0x5182A2E: clone (clone.S:71)
==3517==    by 0x4E49EC4: create_thread (createthread.c:100)
==3517==    by 0x4E49EC4: pthread_create@@GLIBC_2.2.5 (pthread_create.c:797)
==3517==    by 0x4C36A27: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==3517==    by 0x10936E: init_game2 (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x109658: init_game (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x108C04: main (in /home/user42/Bureau/Philosophers/philo/philo)
==3517== 
==3517== ----------------------------------------------------------------
==3517== 
==3517== Thread #2 unlocked a not-locked lock at 0x5452B88
==3517==    at 0x4C34534: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==3517==    by 0x10B212: unlocker_die_mutex (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10B2D8: routine_die (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10A506: show_state (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10AB60: routine_eat2 (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10AD61: routine_eat (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10A00C: loop_routine (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x10A0D6: routine (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x4C36C26: ??? (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==3517==    by 0x4E496DA: start_thread (pthread_create.c:463)
==3517==    by 0x5182A3E: clone (clone.S:95)
==3517==  Lock at 0x5452B88 was first observed
==3517==    at 0x4C37F2A: pthread_mutex_init (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==3517==    by 0x10962D: init_game (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x108C04: main (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==  Address 0x5452b88 is 40 bytes inside a block of size 200 alloc'd
==3517==    at 0x4C30F2F: malloc (in /usr/lib/valgrind/vgpreload_helgrind-amd64-linux.so)
==3517==    by 0x1095C2: init_game (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==    by 0x108C04: main (in /home/user42/Bureau/Philosophers/philo/philo)
==3517==  Block was alloc'd by thread #1
==3517== 
==3517== 
==3517== ----------------------------------------------------------------
==3517== 
==3517== Thread #2: Exiting thread still holds 1 lock
==3517==    at 0x4E49796: __exit_thread (exit-thread.h:36)
==3517==    by 0x4E49796: start_thread (pthread_create.c:583)
==3517==    by 0x5182A3E: clone (clone.S:95)
==3517== 
==3517== 
==3517== For counts of detected and suppressed errors, rerun with: -v
==3517== Use --history-level=approx or =none to gain increased speed, at
==3517== the cost of reduced accuracy of conflicting-access information
==3517== ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 5746190 from 293)

